[pytest]
# Tells pytest to include the root directory in the search path
pythonpath = .

# Tells pytest where to look for tests
testpaths = tests

# Simplifies the output and makes it verbose
addopts = -v --tb=short

# Custom markers
markers =
    skip: marks tests as skipped (deselect with '-m "not skip"')
    live: marks tests that require a real database (run with 'pytest -m live')